### ISSUE TITLE
Window resolution abnormal 

### ISSUE THREAD

**Issue by syslot** [andrewnguonly/Lumos#159] opened 2024-04-09 03:36 UTC
When I update the new version 1.0.13, the extension's window resuolution is abnormal. 
<img width="244" alt="Screenshot 2024-04-09 at 11 36 20" src="https://github.com/andrewnguonly/Lumos/assets/5219942/67a5fbe6-33b2-49e8-9470-2aabd588793d">

**Comment by andrewnguonly** [comment] 2024-04-09 04:25
@syslot, thanks for reporting the issue! What browser and browser version are you using?

**Comment by syslot** [comment] 2024-04-09 12:32
I tested this with two browser: 
1. Chrome with Version 122.0.6261.129 (Official Build) (x86_64)
2. Arc Version 1.37.0 (48361) Chromium Engine Version 123.0.6312.106

**Comment by andrewnguonly** [comment] 2024-04-09 14:12
I'm testing with Chrome version `123.0.6312.107` and I can't reproduce the issue. I'll test with Arc next. The screenshot looks like it's from Arc.

**Comment by syslot** [comment] 2024-04-10 02:35
this pic is captured in chrome

**Comment by andrewnguonly** [comment] 2024-04-10 03:42
Can you inspect popup window and check the `width` of the `popup` class? What does it show?

I can reproduce the issue if I remove the `width` attribute of the `popup` class.
```css
.popup {
  /* width: 550px; */
  padding: 10px;
}
```

**Comment by syslot** [comment] 2024-04-10 07:18
It doesn't match the situation you described. For the reason that I can't find the popup segment in style. Is it unexpected width of the container?

**Comment by andrewnguonly** [comment] 2024-04-10 14:15
The expected width of the popup is `550px`, as specified in `Popup.css`. If you don't see the `popup` class, then something is very wrong 😅 

Can you try deleting the `dist` folder/files and rebuilding the entire app (i.e. `npm run build`)?

**Comment by syslot** [comment] 2024-04-11 12:02
> The expected width of the popup is `550px`, as specified in `Popup.css`. If you don't see the `popup` class, then something is very wrong 😅
> 
> Can you try deleting the `dist` folder/files and rebuilding the entire app (i.e. `npm run build`)?

Thanks for your reply. 
I'veA fellowed your advice , remove all project source code and re-clone it. After execute cmd : npm run build and load the dist fold,  I found two errors in my extension page; here are :

<img width="662" alt="image" src="https://github.com/andrewnguonly/Lumos/assets/5219942/a73b3ad2-1648-4871-830e-13f427ee3c59">
<img width="657" alt="image" src="https://github.com/andrewnguonly/Lumos/assets/5219942/0120450c-c064-4811-8ca7-a0f1523faa3e">


Is this the problem?

**Comment by andrewnguonly** [comment] 2024-04-14 03:02
It's possible that there's a CSS class name collision with another extension. I'm going to update the class names to see if that helps.

**Comment by andrewnguonly** [comment] 2024-04-14 04:10
@syslot, can you try version `1.0.14`?

**Comment by andrewnguonly** [comment] 2024-04-26 14:29
Hey @syslot, just checking in. Does version `1.0.14` resolve your issue?

**Comment by andrewnguonly** [comment] 2024-05-18 21:14
Closing this issue for now. @syslot, if the issue is still present in the latest release, please re-open this issue. Thanks!

**Closed by andrewnguonly** 2024-05-18 21:14 UTC
